# Generated by Django 3.2.16 on 2022-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_name', models.CharField(max_length=255, verbose_name='Марка и модель авто')),
                ('car_production_year', models.PositiveSmallIntegerField(verbose_name='Год выпуска авто')),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Объем двигателя')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
        ),
    ]
