# Generated by Django 3.2.16 on 2022-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработана ли заявка'),
        ),
    ]
