# Generated by Django 3.2.16 on 2022-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicerequest_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-11-21 10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
